default:
  image: $CI_REGISTRY_IMAGE/builder:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_TLS_CERTDIR: ""
  BUILDER_IMAGE_NAME: $CI_REGISTRY_IMAGE/builder:latest
  BUILDER_IMAGE_ARM_NAME: $CI_REGISTRY_IMAGE/builder_arm:latest

stages:
  - build
  - lint
  - test

build-builder-image:
  stage: build
  image: docker:latest
  needs: []
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $BUILDER_IMAGE_NAME -f builder/Dockerfile builder/
    - docker push $BUILDER_IMAGE_NAME
  when: manual

compile-amd64:
  stage: build
  needs: []
  script:
    - make build
  artifacts:
    paths:
      - bee
    expire_in: 1 week

build-builder-image-arm:
  stage: build
  image: docker:latest
  needs: []
  services:
    - name: docker:dind
      alias: docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $BUILDER_IMAGE_ARM_NAME -f builder_arm/Dockerfile builder_arm/
    - docker push $BUILDER_IMAGE_ARM_NAME
  when: manual

compile-arm:
  stage: build
  image: $BUILDER_IMAGE_ARM_NAME
  needs: []
  script:
    - make build-arm
  artifacts:
    paths:
      - bee
    expire_in: 1 week

golangci-lint:
  stage: lint
  needs: []
  script:
    - make lint

test:
  stage: test
  needs: []
  script:
    - make coverhtml
  artifacts:
    paths:
      - coverage_unit.html
    expire_in: 1 week
    expose_as: coverageReport
