FROM golang:bullseye

# Install dependencies for cross compilation
RUN dpkg --add-architecture armhf && \
    apt update && \
    apt install -y gcc-arm-linux-gnueabihf libpcap-dev:armhf && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*
